### ISSUE TITLE
Postprocessing error for parenthetical mismatch.

### ISSUE THREAD

**Issue by ChristopherCaradonna** [NatLabRockies/ComStock#210]
Postprocessing error for parenthetical mismatch on 'postproc_per_upgrade' branch. The error and section of code are shown below.

(comstockpostproc) C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing>python compare_upgrades.py
Traceback (most recent call last):
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\compare_upgrades.py", line 6, in <module>
    import comstockpostproc as cspp
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\comstockpostproc\__init__.py", line 3, in <module>
    from .comstock import ComStock
  File "C:\Users\ccaradon\Documents\GitHub\ComStock\postprocessing\comstockpostproc\comstock.py", line 2061
    logger.info(f'{
                   ^
SyntaxError: EOL while scanning string literal

https://github.com/NREL/ComStock/blob/postproc_per_upgrade/postprocessing/comstockpostproc/comstock.py#L2061-L2065

**Comment by wenyikuang** [comment]
fixed in this commit:
https://github.com/NREL/ComStock/commit/ec34a3c2ed4f5eddbd3599dc136044a65759e760

Due to the misuse of the " and ' in the f-str.

**Comment by wenyikuang** [comment]
Feel free to re-open the issue :)
