### ISSUE TITLE
fix the integrated test

### ISSUE THREAD

**Issue by wenyikuang** [NatLabRockies/ComStock#241]
```buildstock_local bsb-integration-test-baseline.yml

     _ __         _     __,              _ __
    ( /  )    o  //   /(    _/_       / ( /  )     _/_    /
     /--< , ,,  // __/  `.  /  __ _, /<  /--< __,  /  _, /
    /___/(_/_(_(/_(_/_(___)(__(_)(__/ |_/___/(_/(_(__(__/ /_
      Executing BuildStock projects with grace since 2018


Traceback (most recent call last):
  File "/usr/local/bin/buildstock_local", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/utils.py", line 120, in run_with_error_capture
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/local.py", line 456, in main
    LocalBatch.validate_project(args.project_filename)
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/local.py", line 167, in validate_project
    super(cls, cls).validate_project(project_file)
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/base.py", line 268, in validate_project
    assert cls.validate_sampler(project_file)
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/base.py", line 333, in validate_sampler
    return BuildStockBatchBase.validate_buildstock_csv(project_file, buildstock_df)
  File "/usr/local/lib/python3.8/site-packages/buildstockbatch/base.py", line 357, in validate_buildstock_csv
    raise ValidationError("\n".join(errors))
buildstockbatch.exc.ValidationError: Column rentable_area in buildstock_csv is not available in options_lookup.tsv

```

**Comment by wenyikuang** [comment]
Looks like /Comstock/resources/options_lookup.tsv need update follow with `ymls/../samples/bsb-integration-test.csv` or vice versa.

**Comment by rHorsey** [comment]
@wenyikuang  which branches of bsb and comstock?

**Comment by wenyikuang** [comment]
https://github.com/NREL/buildstockbatch/tree/rHorsey/comstock-23-10-upgrade <- I build the container from here.
The Dockerfile is:
https://github.com/NREL/buildstockbatch/blob/rHorsey/comstock-23-10-upgrade/Dockerfile

**Comment by wenyikuang** [comment]
- rebase from main branch of bsb and rebuild from there
-- may need change the dbuilstock.csv path to there


Problems may faced:
- number of sample is too low and facing divide 0 issue

Could be tweaked:
- Run some fast measure to do sanity check instead of slow ones.

**Comment by asparke2** [comment]
@wenyikuang yes, bsb-integration-test.csv needs to be updated. Pull a subset of the rows from this file: on Kestrel: `/kfs2/projects/eusscom/samples/euss_fy25/2024_r2/buildstock_20241103-1011_v98_2018_hhorsey_149325_hardsize.csv`

**Comment by wenyikuang** [comment]
@asparke2 I didn't update the csv files but after I merged the develop branch on bsb it looks works(with small tweaks), let me update the csv and re-run it.

**Comment by wenyikuang** [comment]
I have:
- updated the docker image of `kuangwenyi/buildstock_tools:ry-branch`
- Done some modification in the `https://github.com/NREL/ComStock/tree/wenyi/fix-ci`
- Run several tests in the jenkins: https://ci.openstudio.net/job/comstock-internal/job/wenyi%252Ffix-ci/19/ 

TODO:
- Fix the ComStock wide.csv export, where is should go??
- Make the cbci jenkins script changes to main branch
