### ISSUE TITLE
Geometry error - cannot compute plane

### ISSUE THREAD

**Issue by mpraprost** [NatLabRockies/ComStock#50]
Prevalent in ~1% of models

[utilities.Plane] <Fatal> Cannot compute plane for points [[-3.048, -7.62, 0], [-3.048, -3.048, 0], [-3.048, -3.048, 0], [-3.048, -7.62, 0]]
[openstudio.model.PlanarSurface] <Error> Could not compute plane for vertices for 'Surface 73'.
[openstudio.model.Surface] <Error> Cannot compute default Surface properties.
[openstudio.model.PlanarSurface] <Fatal> Cannot create a surface with vertices [[-3.048, -7.62, 0], [-3.048, -3.048, 0], [-3.048, -3.048, 0], [-3.048, -7.62, 0]]
[openstudio.measure.OSRunner] <Error> Measure Failed with Error: /lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:886:in `fromFloorPrint'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:886:in `makeSpaceFromPolygon'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:828:in `block (2 levels) in makeSpacesFromPolygons'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:816:in `each'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:816:in `block in makeSpacesFromPolygons'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:767:in `each'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:767:in `each_with_index'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_geometry.rb:767:in `makeSpacesFromPolygons'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_model_generation.rb:1178:in `create_bar'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_model_generation.rb:1714:in `bar_hash_setup_run'
/lib/resources/measures/create_bar_from_building_type_ratios/resources/os_lib_model_generation.rb:2400:in `bar_from_building_type_ratios'

**Comment by mdahlhausen** [comment]
The fix for this is to not have buildings with very tiny spaces. This happens because the building types have fixed % space type ratios, and in some small buildings, that can create a lot of small spaces. Outpatient for example.
